### ISSUE TITLE
Forwardslashes in uri causes logseq page to not be created properly

### ISSUE THREAD

**Issue by sfgartland** [c6p/logseq-hypothesis#8]
When trying to load annotations from a webpage the logseq page does not get created properly. That is, it is searchable when pressing Ctrl+k, but it is not loaded properly, and it does not seem to be written to a file on disk, annotations are not loaded either. I suspect it might have to do with the url name not being compatible with the naming scheme of my filesystem (NTFS), but I haven't looked to much into it.

Example of URL that causes the problem: https://plato.stanford.edu/archives/fall2021/entries/rationalism-empiricism/

I've created a temporary workaround in a fork: https://github.com/sfgartland/logseq-hypothesis

**Comment by c6p** [comment]
Hi @sfgartland. You may be onto something, though I won't have my pc with me for a month. It is looking good, but I can't test for now. If you have tested the fix throughly and vouch for the changes, I can merge a PR.

**Comment by sfgartland** [comment]
@c6p I haven't had time to properly verify the changes yet. I was also holding off on it as I was thinking of making a bigger change to make the plugin more future proof. **What do you think of using some kind of page tag as a identifier for each page, such that the title is free to be named whatever?** (I think e.g. the title of the annotated page would make more sense from a usability perspective) Such an approach would in my opinion make the plugin more robust for any further features anyone would like to add, as well as making the synced pages more independent from changes in logseq's naming schemes.

note: By page tag i mean something like `hypothesis-id:: [whatever]` in the first block of the logseq page.

I haven't looked so much into the hypothesis api so I don't know what would be best suited as a id, but was thinking the uri would be a good candidate as it seems to be unique for each annotated page. Or do you have any other suggestions?

**Comment by c6p** [comment]
Replacing the first block with page properties was also on my mind, for v0.2.1. Something like
```md
uri::
title::
```
[`title`](https://docs.logseq.com/#/page/custom%20page%20title) is a special property in Logseq though it would also resolve #6, I'm not sure whether it would cause clashes with other pages, maybe we can prepend the title with `hid__` or something to prevent that, or first check whether the page exists then append a number or else, we should think about that.

Another thing we need to check, does org-mode require `#+TITLE:` syntax for page-properties, or also ok with `title::`?

As far as I remember, annotations have IDs in hypothesis, URIs do not, however since a page collects all annotations for a URI, using it as a unique identifier would be best, as you have suggested. At lines 187 and 204, page properties could be set instead.
https://github.com/c6p/logseq-hypothesis/blob/3cdc3c35a48951976f1035dcdddac65db74623f9/src/App.vue#L187

In the end, it would be great, though need some consideration first.

**Comment by sfgartland** [comment]
I've implemented a page-prop system here https://github.com/sfgartland/logseq-hypothesis/commit/2cd6156f780ed589f31f3aebc3bdf7e86d9804ef. I haven't tested much yet, but atleast for myself it works fine, and I think it is future proof. 

I also solved #6 as a byproduct. With my implementation the title is set to the hypothesis title when the page is created, then the user is free to edit it later as he/she wishes.

One thing that remains for sure is to validate the changes for users using org-mode files.

**Comment by c6p** [comment]
Cool👏, still can't try, but it is looking great.

I like the `naming-scheme` property, later a page action may be provided to move/modify the page to the new/preferred naming scheme.

Only thing, [hypothesis API](https://h.readthedocs.io/en/latest/api-reference/#tag/annotations) uses `uri` for that property and reserves `id` for annotation ids. I have used -for better or worse- `hid` for annotation id to not clash with other props. In my opinion, `uri` or `hypothesis-uri` would clarify the intent better than ` hypothesis-id`.

Also, I think `[?b :block/name _]` can be added to datascript query to replace `finds.filter` below.

Page-property approach does not assume a fixed page name, will be more stable. Thank you for your work, again.

**Comment by sfgartland** [comment]
You have point regarding the `hypothesis-id` name. The reason I went for `hypothesis-id` was because I thought it made more sense for the end-user as it's function is actually to identify the page, and the end-user won't have any contact with hypothesis API anyways. Also I felt it made it more clear to the end-user that is was something that shouldn't be changed. That was my rational, but if you like the idea of calling it `hypothesis-uri` better we could of course change it!

Your probably right about the datascript query, the query I included in the code was just something I made by cutting and pasting pieces from the wiki until it worked🙈 So feel free to improve upon it as I have no idea how the query language actually works.

Also as a end note, I'm working on a modification so that the blocks will be matched by the annotation id stored in their properties, and such can be updated properly when changed in hypothesis. I don't think they update properly now. With the system I had in mind it would also be possible for the user to make modifications to the annotations in logseq, but I will have to see how that turns out😊

And I guess I (and everyone else using the plugin) should be the ones thankning you for the work!

**Comment by c6p** [comment]
Thank you for your nice words.

Since the identifier is URI in this case, I think `hypothesis-uri` would be better.

Your datascript is good. https://udayv.com/blog/2016-04-28-datascript101/ and http://www.learndatalogtoday.org/ are great resources. I think they are listed somewhere in logseq wiki or discord, though if you don't know about them, here they are.

Yes, currently modifications to annotations are not reflected, it was planned but not yet implemented. `updated` logseq property is actually added to check in the future for modifications. Though I'm not sure whether it is necessary. We may altogether just update everything with a matching `id`. I'm fine with either way.

While implementing, the only issue to take care is the fact that deleted annotations are not returned by hypothes.is API, as if they never have existed. If they are referenced by other notes, they are shown in logseq tree as deleted (trashcan icon). Since I'm not doing a full refresh to gather all annotations, but only fetching annotations after a timestamp ([`search_after`](https://h.readthedocs.io/en/latest/api-reference/#tag/annotations/paths/~1search/get)), hypothes.is does not give us any way to discern deleted annotations as far as I know. I think we have 2 options here. First, 'a full refresh button' to fetch everything from scratch, which a user can use time to time, both to clean messed up settings and find out deleted annotations. In this case deleted annotations should not be purged but marked as deleted, since respective blocks may be referenced in logseq, we do not want to break anything. Second, the button on page bar could fetch all annotations for current URI ([using `uri` parameter](https://h.readthedocs.io/en/latest/api-reference/#tag/annotations/paths/~1search/get)) disregarding starting time, so we can mark missing annotations as deleted. Currently, `page bar button` just does what `fetch updates` button does, then adds new annotations to the current page. 

Handling deletions may be troublesome, and I think is not as urgent as representing modifications. In the first phase we can just update modifications as you said, ignoring deletions.

> With the system I had in mind it would also be possible for the user to make modifications to the annotations in logseq.

Do you intend to update hypothes.is annotations via API with user modifications (which would be great), or is it a way to store them locally side by side with annotations? I'm eagerly waiting for your solution. :heart_eyes:

Cheers

**Comment by PixelShober** [comment]
Hey there guys! 
@c6p your plugin is pure love but could some of you guys upload a new release which fix the URL Naming in the Title? 
Thank you already so much for your great work <3

**Comment by c6p** [comment]
Thank you, @LouisMehring. Sorry for the delay, everyone.

I'm going to merge @sfgartland's brilliant solution this weekend at the latest, hopefully sooner.

**Comment by PixelShober** [comment]
@c6p @sfgartland Thanks a lot! 
Can't wait to use the plugin 💯

**Comment by sfgartland** [comment]
Just as a note @LouisMehring, you can also sideload the plugin by downloading my version of the repo, then using the developer mode in Logseq, I'm sure there's some more info about it on Logseq's pages😊

**Comment by PixelShober** [comment]
Sadly I am not so much into Vue so I need to build the version from @sfgartland first right? 
I already loaded your latest release into LogSeq over the Developer Options!

**Comment by c6p** [comment]
@sfgartland, I've made some changes to make it work with the org files and the old naming scheme.  Also, `hypothesis-id` has become `hypothesis-uri`.  Thank you for your work. I'm looking forward to your further changes.

I hope all is well with the release.

Cheers :beers:
